apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms3
  template:
    metadata:
      labels:
        app: ms3
    spec:
      containers:
      - name: ms3
        image: jeffyf/ms3
        imagePullPolicy: Always
        ports:
          - name: inv-port
            containerPort: 2001
