apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-inventory-ms
  namespace: krx-kitchen-inventory-ms
  labels:
    app: krx-kitchen-inventory-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: krx-kitchen-inventory-ms
  template:
    metadata:
      labels:
        app: krx-kitchen-inventory-ms
    spec:
      containers:
      - name: kitchen-inventory-ms-container
        image: zigzag32/kitchen-inventory-microservice
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports: 
        - name: krx-port
          containerPort: 8080
        #envFrom:
        #- configMapRef:
        #    name: my-config