apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  namespace: krx-recommend-recipe-ms
type: Opaque
data:
  api-key: c2stcHJvai1WbTdCbEd0SGpDNkQ0RmlYUVl5WFQzQmxia0ZKRjAybW1Jc2N0QVdhOEx5dUQ2ZTE=
  #sk-proj-Vm7BlGtHjC6D4FiXQYyXT3BlbkFJF02mmIsctAWa8LyuD6e1  # 这里需要将 API Key 编码成 Base64 格式
