apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3
  namespace: krx-recommend-recipe-ms
  labels:
    app: ms3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms3
  template:
    metadata:
      labels:
        app: ms3
    spec:
      containers:
      - name: ms3
        image: jeffyf/ms3
        imagePullPolicy: Always
        ports:
          - name: ms3-port
            containerPort: 2001
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-api-key  # Secret 对象的名称
                key: api-key           # Secret 中的键
